apiVersion: apps/v1
kind: Deployment
metadata:
 name: {{ include "neverending-blog.fullname" . }}-postgresql
spec:
 selector:
   matchLabels:
     app: {{ include "neverending-blog.fullname" . }}-postgresql-container
 template:
   metadata:
     labels:
       app: {{ include "neverending-blog.fullname" . }}-postgresql-container
   spec:
     containers:
       - name: {{ include "neverending-blog.fullname" . }}-postgresql-container
         image: debezium/postgres:latest
         ports:
           - containerPort: {{ .Values.database.service_port }}
         env:
           - name: POSTGRES_USER
             value: {{ .Values.database.user }}
           - name: POSTGRES_PASSWORD
             value: {{ .Values.database.password }}
           - name: POSTGRES_DB
             value: {{ .Values.database.name }}
        
---
apiVersion: v1
kind: Service
metadata:
 name: "{{ .Values.database.service_host }}"
spec:
 ports:
   - port: {{ .Values.database.service_port }}
 selector:
   app: {{ include "neverending-blog.fullname" . }}-postgresql-container