apiVersion: v1
kind: Secret
metadata:
  annotations:
    template.openshift.io/expose-database_name: '{.data[''database-name'']}'
    template.openshift.io/expose-password: '{.data[''database-password'']}'
    template.openshift.io/expose-root_password: '{.data[''database-root-password'']}'
    template.openshift.io/expose-username: '{.data[''database-user'']}'
  labels:
    template: mysql-ephemeral-template
  name: {{ .Values.database.service_host }}
stringData:
  database-name: {{ .Values.database.name }}
  database-password: {{ .Values.database.password }}
  database-root-password: {{ .Values.database.root_password }}
  database-user: {{ .Values.database.user }}
  database-operations-user: {{ .Values.database.operations_user }}
  database-operations-password: {{ .Values.database.operations_password }}
