apiVersion: v1
kind: DeploymentConfig
metadata:
  annotations:
    template.alpha.openshift.io/wait-for-ready: "true"
  labels:
    template: mysql-ephemeral-template
  name: {{ .Values.database.service_host }}
spec:
  replicas: 1
  selector:
    name: {{ .Values.database.service_host }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        name: {{ .Values.database.service_host }}
    spec:
      containers:
      - capabilities: {}
        env:
        - name: MYSQL_BINLOG_FORMAT
          value: row
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              key: database-user
              name: {{ .Values.database.service_host }}
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              key: database-password
              name: {{ .Values.database.service_host }}
        - name: MYSQL_OPERATIONS_USER
          valueFrom:
            secretKeyRef:
              key: database-operations-user
              name: {{ .Values.database.service_host }}
        - name: MYSQL_OPERATIONS_PASSWORD
          valueFrom:
            secretKeyRef:
              key: database-operations-password
              name: {{ .Values.database.service_host }}
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              key: database-root-password
              name: {{ .Values.database.service_host }}
        - name: MYSQL_DATABASE
          valueFrom:
            secretKeyRef:
              key: database-name
              name: {{ .Values.database.service_host }}
        image: debezium/example-mysql
        imagePullPolicy: IfNotPresent
        livenessProbe:
          initialDelaySeconds: 30
          tcpSocket:
            port: 3306
          timeoutSeconds: 1
        name: mysql
        ports:
        - containerPort: {{ .Values.database.service_port }}
          protocol: TCP
        readinessProbe:
          exec:
            command:
            - /bin/sh
            - -i
            - -c
            - MYSQL_PWD="$MYSQL_PASSWORD" mysql -h 127.0.0.1 -u $MYSQL_USER -D $MYSQL_DATABASE
              -e 'SELECT 1'
          initialDelaySeconds: 5
          timeoutSeconds: 1
        resources:
          limits:
            memory: 512Mi
        securityContext:
          capabilities: {}
          privileged: false
        terminationMessagePath: /dev/termination-log
        volumeMounts:
        - mountPath: /var/lib/mysql
          name: {{ .Values.database.service_host }}-data
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      volumes:
      - emptyDir:
          medium: ""
        name: {{ .Values.database.service_host }}-data
  triggers:
  - type: ConfigChange
status: {}
